      PROGRAM ARBOL_BINARIO
      IMPLICIT NONE
      INTEGER, PARAMETER :: NMAX = 100
      INTEGER :: VALOR(NMAX), IZQ(NMAX), DER(NMAX)
      INTEGER :: RAIZ, DISP, I
      COMMON /ARBOL/ VALOR, IZQ, DER, RAIZ, DISP


      RAIZ = 0
      DISP = 1
      DO I = 1, NMAX
         IZQ(I) = 0
         DER(I) = 0
      END DO

      CALL INSERTAR(RAIZ, 10)
      CALL INSERTAR(RAIZ, 8)
      CALL INSERTAR(RAIZ, 13)
      CALL INSERTAR(RAIZ, 5)
      CALL INSERTAR(RAIZ, 9)
      CALL INSERTAR(RAIZ, 12)
      CALL INSERTAR(RAIZ, 20)

      PRINT *, 'PREORDEN:'
      CALL PREORDEN(RAIZ)

      PRINT *, 'INORDEN:'
      CALL INORDEN(RAIZ)

      PRINT *, 'POSTORDEN:'
      CALL POSTORDEN(RAIZ)
      
      PRINT *, "ENTER PPARA SALIR"
      READ(*,*)

      END PROGRAM ARBOL_BINARIO

      RECURSIVE SUBROUTINE INSERTAR(NODO, X)
      IMPLICIT NONE
      INTEGER NODO, X
      INTEGER, PARAMETER :: NMAX = 100
      INTEGER :: VALOR(NMAX), IZQ(NMAX), DER(NMAX)
      INTEGER :: RAIZ, DISP
      COMMON /ARBOL/ VALOR, IZQ, DER, RAIZ, DISP

      IF (NODO .EQ. 0) THEN
         NODO = DISP
         VALOR(NODO) = X
         IZQ(NODO) = 0
         DER(NODO) = 0
         DISP = DISP + 1
      ELSE IF (X .LT. VALOR(NODO)) THEN
         CALL INSERTAR(IZQ(NODO), X)
      ELSE
         CALL INSERTAR(DER(NODO), X)
      END IF

      END SUBROUTINE INSERTAR

      RECURSIVE SUBROUTINE PREORDEN(NODO)
      IMPLICIT NONE
      INTEGER NODO
      INTEGER, PARAMETER :: NMAX = 100
      INTEGER :: VALOR(NMAX), IZQ(NMAX), DER(NMAX)
      INTEGER :: RAIZ, DISP
      COMMON /ARBOL/ VALOR, IZQ, DER, RAIZ, DISP

      IF (NODO .NE. 0) THEN
         PRINT *, VALOR(NODO)
         CALL PREORDEN(IZQ(NODO))
         CALL PREORDEN(DER(NODO))
      END IF
      END SUBROUTINE PREORDEN

      RECURSIVE SUBROUTINE INORDEN(NODO)
      IMPLICIT NONE
      INTEGER NODO
      INTEGER, PARAMETER :: NMAX = 100
      INTEGER :: VALOR(NMAX), IZQ(NMAX), DER(NMAX)
      INTEGER :: RAIZ, DISP
      COMMON /ARBOL/ VALOR, IZQ, DER, RAIZ, DISP

      IF (NODO .NE. 0) THEN
         CALL INORDEN(IZQ(NODO))
         PRINT *, VALOR(NODO)
         CALL INORDEN(DER(NODO))
      END IF
      END SUBROUTINE INORDEN

      RECURSIVE SUBROUTINE POSTORDEN(NODO)
      IMPLICIT NONE
      INTEGER NODO
      INTEGER, PARAMETER :: NMAX = 100
      INTEGER :: VALOR(NMAX), IZQ(NMAX), DER(NMAX)
      INTEGER :: RAIZ, DISP
      COMMON /ARBOL/ VALOR, IZQ, DER, RAIZ, DISP

      IF (NODO .NE. 0) THEN
         CALL POSTORDEN(IZQ(NODO))
         CALL POSTORDEN(DER(NODO))
         PRINT *, VALOR(NODO)
      END IF
      END SUBROUTINE POSTORDEN

